version: '3.4'

services:
  cyberdb:
    container_name: cyberdb
    environment:
        SA_PASSWORD: "Sw!12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
  cyber:
    container_name: cyber.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:CyberConnectionString=Server=cyberdb;Database=CyberDb;User Id=sa;Password=Sw!12345678"  
    ports:
      - "80"
    depends_on:
      - cyberdb
