// <auto-generated />
using Cyber.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cyber.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20220923155612_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cyber.Model.Alert", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Title", "Description", "Severity")
                        .IsUnique();

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("Cyber.Model.AlertIP", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlertId")
                        .HasColumnType("int");

                    b.Property<int>("IPAddressId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IPAddressId");

                    b.HasIndex("AlertId", "IPAddressId")
                        .IsUnique();

                    b.ToTable("AlertIps");
                });

            modelBuilder.Entity("Cyber.Model.IPAddress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BlackListed")
                        .HasColumnType("bit");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IPCounter")
                        .HasColumnType("int");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IP")
                        .IsUnique();

                    b.ToTable("IPAddress");
                });

            modelBuilder.Entity("Cyber.Model.AlertIP", b =>
                {
                    b.HasOne("Cyber.Model.Alert", "Alert")
                        .WithMany("AlertIPs")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cyber.Model.IPAddress", "IPAddress")
                        .WithMany("AlertIPs")
                        .HasForeignKey("IPAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");

                    b.Navigation("IPAddress");
                });

            modelBuilder.Entity("Cyber.Model.Alert", b =>
                {
                    b.Navigation("AlertIPs");
                });

            modelBuilder.Entity("Cyber.Model.IPAddress", b =>
                {
                    b.Navigation("AlertIPs");
                });
#pragma warning restore 612, 618
        }
    }
}
